@extends('layouts.master')
@section('content')
<section class="content"> 
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-danger">
                <div class="box-header">
                    <h3 class="box-title">Voucher Card Details</h3>

                    @if (session()->has('message'))
                    <br>
                    <div class = "alert alert-success col-md-12">
                        <ul>
                          <li>{{Session::get('message')}}</li>
                      </ul>
                  </div>
                  @endif
              </div>
              <!-- /.box-header --> 
              <div class="box-body"  >

                 <div class="col-md-12">
                <table>
                
              
                <?php
                if($voucher->voucher_image == ''){
                  ?>
                <tr style="height: 50px;">
                    <td style="width: 200px;"><b>Voucher Image </b></td>
                    <td></td>
                  </tr>
                <?php }else{ ?>

                  <tr style="height: 50px;">
                    <td style="width: 200px;"><b>Voucher Image</b></td>
                    <td><img  width="200px"  height="100px" src="{{$voucher->voucher_image}}"><br/><br/></td>
                  </tr>
                <?php } ?>
            
                </table>   
                </div>

              <table id="example1" class="table table-bordered table-striped" >
                <thead>
                <tr>
                  <th>Sr. No.</th>
                   <th>Generated By User</th>
                  <th>Voucher Code </th>
                  <th>Bar Code</th>
                  <th>Reedemed</th>
                  <th>Voucher Card Back</th>
                 
                </tr>
                </thead>
                <tbody>
              
              <?php $count = 0; 

              ?>
                
                @forelse($voucher_code as $key => $voucher_codes)

                <?php 

                $count++; ?>

                <tr>
                  <td>  
                     {{$count}}
                  </td>
                  <td>  
                     {{$voucher_codes['username']}}
                  </td>
                 
                   <td >{{$voucher_codes['voucher_code']}}</td>
                 
                  <td >
                    <img src="data:image/png;base64,{{DNS1D::getBarcodePNG($voucher_codes['voucher_code'], 'C128')}}" alt="barcode" />
                   </td>
                    <td >
                    <a style="float: left;margin-right: 10px;" title="View" class="btn btn-primary" href="{{url('voucher/redeem/'.@$voucher_codes['voucher_code'])}}"><span class="glyphicon glyphicon-eye-open"></span></a>
                   </td>
                      <td >
                    <a style="float: left;margin-right: 10px;" title="View" class="btn btn-primary" href="{{url('/voucher/viewback/'.@$voucher_codes['voucher_code'])}}" ><span class="glyphicon glyphicon-eye-open"></span></a>
                   </td>
                </tr>
                 @empty
                <tr><td colspan="4">No Records!!!</td></tr>
                @endforelse
               
                </tbody>
             </table>
           


              </div>
            </div>
          </div>


        </div>
<!-- /.row -->
</section>


@endsection
@section('page_scripts')
<script>
    var token = "{{ csrf_token() }}";
</script>
<script>
function goBack() {
  window.history.back();
}
</script>
<script>
    $(function () {
        $('#example1').DataTable();
        $('#example2').DataTable({
            'paging': true,
            'lengthChange': true,
            'searching': true,
            'ordering': false,
            'info': true,
            'autoWidth': false
        });
        
        $(".lp-change-password-btn").on("click", function () {
            var id = $(this).attr("data-id");
            var url = "{{url('admin/change-user-password')}}" + "/" + id;
            $("#change-password-modal form").attr('action', url);
            $("#change-password-modal").modal('show');
        });
    </script>
    @endsection